#pragma once
#include <compiler/grammar/induced/grammar_bounds_v1.hh>
#include <cstdint>

namespace cellshard::compiler::grammar::induced {
struct canonical_symbol_v1{induced_identity_v1 operation_identity{},structure_identity{},domain_identity{},order_identity{};std::uint64_t structure_generation=0;};
struct canonical_induced_production_v1{const canonical_symbol_v1*symbols=nullptr;std::uint64_t symbol_count=0;induced_identity_v1 production_identity{},candidate_identity{},trace_identity{};std::uint64_t observation_generation=0,encoding_version=1;};
enum class canonical_production_code_v1:std::uint32_t{encoded,invalid_input,invalid_candidate,invalid_identity,missing_output,insufficient_output,mismatch};
struct canonical_production_result_v1{canonical_production_code_v1 code=canonical_production_code_v1::encoded;canonical_induced_production_v1 production{};std::uint64_t index=0;[[nodiscard]]constexpr bool encoded()const noexcept{return code==canonical_production_code_v1::encoded;}};
[[nodiscard]]constexpr canonical_production_result_v1 encode_canonical_production_v1(induced_grammar_observation_view_v1 input,repeated_production_candidate_v1 candidate,induced_identity_v1 production_identity,canonical_symbol_v1*out,std::uint64_t capacity)noexcept{if(!validate_induced_grammar_observations_v1(input).valid())return{canonical_production_code_v1::invalid_input};if(candidate.symbol_count==0||candidate.symbol_count>input.observation_count||candidate.first_begin>input.observation_count-candidate.symbol_count||candidate.second_begin>input.observation_count-candidate.symbol_count||!(candidate.trace_identity==input.trace_identity)||candidate.observation_generation!=input.observation_generation)return{canonical_production_code_v1::invalid_candidate};if(!valid(production_identity)||!valid(candidate.candidate_identity))return{canonical_production_code_v1::invalid_identity};if(out==nullptr)return{canonical_production_code_v1::missing_output,{},candidate.symbol_count};if(capacity<candidate.symbol_count)return{canonical_production_code_v1::insufficient_output,{},candidate.symbol_count};for(std::uint64_t i=0;i<candidate.symbol_count;++i){const auto&a=input.observations[candidate.first_begin+i];const auto&b=input.observations[candidate.second_begin+i];if(!same_structural_symbol_v1(a,b))return{canonical_production_code_v1::mismatch,{},i};out[i]={a.operation_identity,a.structure_identity,a.domain_identity,a.order_identity,a.structure_generation};}return{canonical_production_code_v1::encoded,{out,candidate.symbol_count,production_identity,candidate.candidate_identity,input.trace_identity,input.observation_generation,1},candidate.symbol_count};}
[[nodiscard]]constexpr bool authorizes_execution(canonical_induced_production_v1)noexcept{return false;}
}
