#pragma once
#include <compiler/grammar/induced/flat_dag_comparison_v1.hh>
#include <compiler/grammar/induced/grammar_bounds_v1.hh>
#include <cstdint>

namespace cellshard::compiler::grammar::induced {
struct induced_grammar_receipt_v1{induced_identity_v1 receipt_identity{},production_identity{},candidate_identity{},promotion_evidence_identity{};std::uint64_t observation_generation=0,production_arity=0,production_depth=0;bool flat_fallback_required=true;};
enum class induced_promotion_gate_code_v1:std::uint32_t{promoted,invalid_identity,stale_evidence,invalid_shape,not_promoted,invalid_planted_control,invalid_adversarial_control};
struct induced_promotion_gate_result_v1{induced_promotion_gate_code_v1 code=induced_promotion_gate_code_v1::promoted;induced_grammar_receipt_v1 receipt{};[[nodiscard]]constexpr bool promoted()const noexcept{return code==induced_promotion_gate_code_v1::promoted;}};
[[nodiscard]]constexpr induced_promotion_gate_result_v1 apply_induced_promotion_gate_v1(induced_identity_v1 receipt_identity,canonical_induced_production_v1 production,induced_production_shape_v1 shape,induced_grammar_bounds_v1 bounds,grammar_promotion_evidence_v1 evidence,flat_dag_comparison_v1 planted,flat_dag_comparison_v1 adversarial)noexcept{if(!valid(receipt_identity)||!valid(production.production_identity))return{induced_promotion_gate_code_v1::invalid_identity};if(!(production.candidate_identity==evidence.candidate_identity)||production.observation_generation!=evidence.observation_generation||shape.observation_generation!=evidence.observation_generation||planted.observation_generation!=evidence.observation_generation||adversarial.observation_generation!=evidence.observation_generation)return{induced_promotion_gate_code_v1::stale_evidence};const auto bounded=validate_induced_production_bounds_v1(shape,bounds);if(!bounded.valid()||shape.arity!=production.symbol_count)return{induced_promotion_gate_code_v1::invalid_shape};if(evidence.disposition!=grammar_evidence_disposition_v1::promote)return{induced_promotion_gate_code_v1::not_promoted};const auto planted_result=compare_with_flat_dag_v1(planted);if(!planted_result.compared()||planted.fixture_kind!=fixture_kind_v1::planted_repetition||!planted_result.induced_wins)return{induced_promotion_gate_code_v1::invalid_planted_control};const auto adversarial_result=compare_with_flat_dag_v1(adversarial);if(!adversarial_result.compared()||adversarial.fixture_kind!=fixture_kind_v1::adversarial_unique||adversarial_result.induced_wins)return{induced_promotion_gate_code_v1::invalid_adversarial_control};return{induced_promotion_gate_code_v1::promoted,{receipt_identity,production.production_identity,production.candidate_identity,evidence.evidence_identity,evidence.observation_generation,shape.arity,bounded.computed_depth,true}};}
[[nodiscard]]constexpr bool authorizes_execution(induced_grammar_receipt_v1 r)noexcept{return valid(r.receipt_identity)&&r.observation_generation!=0&&r.flat_fallback_required;}
}
