#pragma once
#include <compiler/grammar/induced/complete_cost_v1.hh>
#include <cstdint>

namespace cellshard::compiler::grammar::induced {
struct mdl_policy_v1{std::uint64_t symbol_reference_bits=0,production_header_bits=0,parameter_bits=0;induced_identity_v1 policy_identity{};};
struct mdl_complexity_v1{induced_identity_v1 candidate_identity{},policy_identity{};std::uint64_t observation_generation=0,model_bits=0,encoded_data_bits=0,total_bits=0,flat_data_bits=0,saved_bits=0;bool compresses=false;};
enum class mdl_code_v1:std::uint32_t{computed,invalid_identity,invalid_input,invalid_policy,overflow};
struct mdl_result_v1{mdl_code_v1 code=mdl_code_v1::computed;mdl_complexity_v1 complexity{};[[nodiscard]]constexpr bool computed()const noexcept{return code==mdl_code_v1::computed;}};
[[nodiscard]]constexpr mdl_result_v1 compute_mdl_complexity_v1(canonical_induced_production_v1 production,frequency_stability_v1 frequency,mdl_policy_v1 policy)noexcept{if(!valid(policy.policy_identity)||!valid(production.production_identity))return{mdl_code_v1::invalid_identity};if(!(production.candidate_identity==frequency.candidate_identity)||production.observation_generation!=frequency.observation_generation||production.symbol_count<2||frequency.total_occurrences==0)return{mdl_code_v1::invalid_input};if(policy.symbol_reference_bits==0||policy.production_header_bits==0)return{mdl_code_v1::invalid_policy};if(production.symbol_count>UINT64_MAX/policy.symbol_reference_bits)return{mdl_code_v1::overflow};const auto body=production.symbol_count*policy.symbol_reference_bits;if(policy.production_header_bits>UINT64_MAX-body||policy.production_header_bits+body>UINT64_MAX-policy.parameter_bits)return{mdl_code_v1::overflow};const auto model=policy.production_header_bits+body+policy.parameter_bits;if(frequency.total_occurrences>UINT64_MAX/policy.symbol_reference_bits)return{mdl_code_v1::overflow};const auto encoded=frequency.total_occurrences*policy.symbol_reference_bits;if(production.symbol_count>UINT64_MAX/frequency.total_occurrences)return{mdl_code_v1::overflow};const auto flat_symbols=production.symbol_count*frequency.total_occurrences;if(flat_symbols>UINT64_MAX/policy.symbol_reference_bits)return{mdl_code_v1::overflow};const auto flat=flat_symbols*policy.symbol_reference_bits;if(model>UINT64_MAX-encoded)return{mdl_code_v1::overflow};const auto total=model+encoded;return{mdl_code_v1::computed,{production.candidate_identity,policy.policy_identity,production.observation_generation,model,encoded,total,flat,total<flat?flat-total:0,total<flat}};}
[[nodiscard]]constexpr bool authorizes_execution(mdl_complexity_v1)noexcept{return false;}
}
