#pragma once
#include <compiler/grammar/induced/mdl_complexity_v1.hh>
#include <cstdint>

namespace cellshard::compiler::grammar::induced {
enum class grammar_evidence_disposition_v1:std::uint32_t{promote=1,demote=2,no_promotion=3};
enum class negative_grammar_reason_v1:std::uint32_t{none=0,unstable_strata=1,no_mdl_gain=2,complete_cost_nonpromotion=3,stale_evidence=4};
struct grammar_promotion_policy_v1{std::uint64_t minimum_stable_numerator=0,minimum_stable_denominator=0,flat_complete_cost_ns=0;};
struct grammar_promotion_evidence_v1{induced_identity_v1 evidence_identity{},candidate_identity{},cost_model_identity{},mdl_policy_identity{};std::uint64_t observation_generation=0;grammar_evidence_disposition_v1 disposition=grammar_evidence_disposition_v1::no_promotion;negative_grammar_reason_v1 negative_reason=negative_grammar_reason_v1::none;};
enum class promotion_evidence_code_v1:std::uint32_t{decided,invalid_identity,invalid_policy,stale_evidence,ratio_overflow};
struct promotion_evidence_result_v1{promotion_evidence_code_v1 code=promotion_evidence_code_v1::decided;grammar_promotion_evidence_v1 evidence{};[[nodiscard]]constexpr bool decided()const noexcept{return code==promotion_evidence_code_v1::decided;}};
[[nodiscard]]constexpr promotion_evidence_result_v1 decide_grammar_promotion_v1(induced_identity_v1 evidence_identity,frequency_stability_v1 frequency,induced_complete_cost_v1 cost,mdl_complexity_v1 mdl,grammar_promotion_policy_v1 policy,bool previously_promoted)noexcept{if(!valid(evidence_identity)||!valid(frequency.candidate_identity))return{promotion_evidence_code_v1::invalid_identity};if(policy.minimum_stable_denominator==0||policy.minimum_stable_numerator>policy.minimum_stable_denominator||policy.flat_complete_cost_ns==0)return{promotion_evidence_code_v1::invalid_policy};if(!(frequency.candidate_identity==cost.candidate_identity)||!(frequency.candidate_identity==mdl.candidate_identity)||frequency.observation_generation!=cost.observation_generation||frequency.observation_generation!=mdl.observation_generation)return{promotion_evidence_code_v1::stale_evidence};if(frequency.stable_strata>UINT64_MAX/policy.minimum_stable_denominator||(policy.minimum_stable_numerator&&frequency.observed_strata>UINT64_MAX/policy.minimum_stable_numerator))return{promotion_evidence_code_v1::ratio_overflow};negative_grammar_reason_v1 reason=negative_grammar_reason_v1::none;if(frequency.stable_strata*policy.minimum_stable_denominator<frequency.observed_strata*policy.minimum_stable_numerator)reason=negative_grammar_reason_v1::unstable_strata;else if(!mdl.compresses)reason=negative_grammar_reason_v1::no_mdl_gain;else if(cost.total_ns>=policy.flat_complete_cost_ns)reason=negative_grammar_reason_v1::complete_cost_nonpromotion;const auto disposition=reason==negative_grammar_reason_v1::none?grammar_evidence_disposition_v1::promote:(previously_promoted?grammar_evidence_disposition_v1::demote:grammar_evidence_disposition_v1::no_promotion);return{promotion_evidence_code_v1::decided,{evidence_identity,frequency.candidate_identity,cost.cost_model_identity,mdl.policy_identity,frequency.observation_generation,disposition,reason}};}
[[nodiscard]]constexpr bool authorizes_execution(grammar_promotion_evidence_v1 x)noexcept{return x.disposition==grammar_evidence_disposition_v1::promote;}
}
